export interface PlantReference {
  name: string;
  type: string;
  spacing: number;
  sunlight: string;
  water: string;
  fertilizer: string;
  companionPlants: string[];
  incompatiblePlants: string[];
}

export const PLANT_DATABASE: PlantReference[] = [
  { name: "Tomato", type: "Vegetable", spacing: 24, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "High phosphorus/potassium", companionPlants: ["Basil", "Marigold", "Carrot", "Onion", "Parsley", "Nasturtium"], incompatiblePlants: ["Potato", "Cabbage", "Corn", "Fennel", "Dill"] },
  { name: "Basil", type: "Herb", spacing: 12, sunlight: "Full Sun", water: "Keep soil moist", fertilizer: "Balanced organic", companionPlants: ["Tomato", "Pepper", "Oregano", "Marigold"], incompatiblePlants: ["Rue", "Sage"] },
  { name: "Carrot", type: "Vegetable", spacing: 3, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Low nitrogen", companionPlants: ["Tomato", "Onion", "Rosemary", "Lettuce", "Sage", "Chives"], incompatiblePlants: ["Dill", "Parsnip", "Celery"] },
  { name: "Marigold", type: "Flower", spacing: 10, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Light balanced fertilizer", companionPlants: ["Tomato", "Cucumber", "Melon", "Squash", "Pepper", "Eggplant"], incompatiblePlants: ["Bean"] },
  { name: "Lettuce", type: "Vegetable", spacing: 6, sunlight: "Partial Shade", water: "Keep soil consistently moist", fertilizer: "High nitrogen", companionPlants: ["Carrot", "Radish", "Strawberry", "Onion", "Chives"], incompatiblePlants: ["Cabbage", "Parsley"] },
  { name: "Pepper", type: "Vegetable", spacing: 18, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, then high phosphorus", companionPlants: ["Basil", "Onion", "Spinach", "Tomato", "Marigold", "Carrot"], incompatiblePlants: ["Bean", "Fennel", "Kohlrabi"] },
  { name: "Cucumber", type: "Vegetable", spacing: 12, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "High nitrogen then balanced", companionPlants: ["Radish", "Sunflower", "Marigold", "Bean", "Pea", "Corn"], incompatiblePlants: ["Potato", "Sage", "Melon"] },
  { name: "Zucchini", type: "Vegetable", spacing: 36, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, rich compost", companionPlants: ["Corn", "Bean", "Nasturtium", "Marigold", "Radish"], incompatiblePlants: ["Potato", "Pumpkin"] },
  { name: "Squash", type: "Vegetable", spacing: 36, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Rich compost, balanced", companionPlants: ["Corn", "Bean", "Marigold", "Nasturtium", "Radish"], incompatiblePlants: ["Potato", "Pumpkin"] },
  { name: "Pumpkin", type: "Vegetable", spacing: 48, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "High phosphorus", companionPlants: ["Corn", "Bean", "Marigold", "Sunflower"], incompatiblePlants: ["Potato", "Squash", "Zucchini"] },
  { name: "Corn", type: "Vegetable", spacing: 12, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "High nitrogen", companionPlants: ["Bean", "Squash", "Pumpkin", "Cucumber", "Pea", "Sunflower"], incompatiblePlants: ["Tomato", "Celery"] },
  { name: "Bean", type: "Vegetable", spacing: 6, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Low nitrogen (fixes own)", companionPlants: ["Corn", "Squash", "Cucumber", "Carrot", "Radish", "Strawberry"], incompatiblePlants: ["Onion", "Garlic", "Pepper", "Fennel", "Marigold"] },
  { name: "Pea", type: "Vegetable", spacing: 4, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Low nitrogen (fixes own)", companionPlants: ["Carrot", "Corn", "Cucumber", "Radish", "Turnip", "Bean"], incompatiblePlants: ["Onion", "Garlic", "Chives"] },
  { name: "Onion", type: "Vegetable", spacing: 4, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, high phosphorus", companionPlants: ["Carrot", "Lettuce", "Tomato", "Pepper", "Beet", "Strawberry"], incompatiblePlants: ["Bean", "Pea", "Sage"] },
  { name: "Garlic", type: "Vegetable", spacing: 6, sunlight: "Full Sun", water: "Moderate, reduce before harvest", fertilizer: "High nitrogen early, stop later", companionPlants: ["Tomato", "Pepper", "Carrot", "Rose", "Strawberry", "Beet"], incompatiblePlants: ["Bean", "Pea", "Asparagus"] },
  { name: "Potato", type: "Vegetable", spacing: 12, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, high potassium", companionPlants: ["Bean", "Corn", "Cabbage", "Horseradish", "Marigold"], incompatiblePlants: ["Tomato", "Cucumber", "Squash", "Sunflower", "Raspberry"] },
  { name: "Sweet Potato", type: "Vegetable", spacing: 12, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Low nitrogen, high potassium", companionPlants: ["Bean", "Thyme", "Marigold", "Oregano"], incompatiblePlants: ["Squash", "Tomato"] },
  { name: "Broccoli", type: "Vegetable", spacing: 18, sunlight: "Full Sun", water: "1-1.5 inches per week", fertilizer: "High nitrogen", companionPlants: ["Onion", "Garlic", "Beet", "Celery", "Dill", "Rosemary"], incompatiblePlants: ["Tomato", "Strawberry", "Pepper"] },
  { name: "Cauliflower", type: "Vegetable", spacing: 18, sunlight: "Full Sun", water: "1-1.5 inches per week", fertilizer: "High nitrogen, rich compost", companionPlants: ["Onion", "Garlic", "Beet", "Celery", "Dill", "Spinach"], incompatiblePlants: ["Tomato", "Strawberry", "Pepper"] },
  { name: "Cabbage", type: "Vegetable", spacing: 18, sunlight: "Full Sun", water: "1-1.5 inches per week", fertilizer: "High nitrogen", companionPlants: ["Onion", "Garlic", "Celery", "Dill", "Thyme", "Potato"], incompatiblePlants: ["Tomato", "Strawberry", "Lettuce"] },
  { name: "Kale", type: "Vegetable", spacing: 18, sunlight: "Full to Partial Sun", water: "1-1.5 inches per week", fertilizer: "High nitrogen, compost", companionPlants: ["Beet", "Celery", "Onion", "Garlic", "Dill", "Nasturtium"], incompatiblePlants: ["Tomato", "Strawberry"] },
  { name: "Spinach", type: "Vegetable", spacing: 6, sunlight: "Partial Shade", water: "1 inch per week", fertilizer: "High nitrogen", companionPlants: ["Strawberry", "Pea", "Bean", "Cauliflower", "Onion", "Radish"], incompatiblePlants: ["Potato"] },
  { name: "Radish", type: "Vegetable", spacing: 2, sunlight: "Full to Partial Sun", water: "Keep soil moist", fertilizer: "Light, balanced", companionPlants: ["Lettuce", "Pea", "Bean", "Cucumber", "Carrot", "Spinach"], incompatiblePlants: ["Hyssop"] },
  { name: "Beet", type: "Vegetable", spacing: 4, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Low nitrogen, high potassium", companionPlants: ["Onion", "Garlic", "Lettuce", "Cabbage", "Broccoli", "Kale"], incompatiblePlants: ["Pole Bean", "Mustard"] },
  { name: "Turnip", type: "Vegetable", spacing: 4, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Light, balanced", companionPlants: ["Pea", "Onion", "Garlic", "Vetch"], incompatiblePlants: ["Potato", "Mustard"] },
  { name: "Celery", type: "Vegetable", spacing: 8, sunlight: "Full to Partial Sun", water: "Keep soil consistently moist", fertilizer: "High nitrogen, rich compost", companionPlants: ["Tomato", "Bean", "Cabbage", "Broccoli", "Cauliflower"], incompatiblePlants: ["Corn", "Parsnip"] },
  { name: "Asparagus", type: "Vegetable", spacing: 18, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, rich compost", companionPlants: ["Tomato", "Parsley", "Basil", "Marigold", "Dill"], incompatiblePlants: ["Garlic", "Onion", "Potato"] },
  { name: "Eggplant", type: "Vegetable", spacing: 24, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, rich compost", companionPlants: ["Bean", "Pepper", "Marigold", "Thyme", "Spinach"], incompatiblePlants: ["Fennel", "Potato"] },
  { name: "Okra", type: "Vegetable", spacing: 12, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, compost", companionPlants: ["Pepper", "Cucumber", "Melon", "Basil", "Sunflower"], incompatiblePlants: ["Sweet Potato"] },
  { name: "Watermelon", type: "Fruit", spacing: 36, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, then high potassium", companionPlants: ["Corn", "Marigold", "Sunflower", "Nasturtium", "Radish"], incompatiblePlants: ["Potato", "Cucumber"] },
  { name: "Cantaloupe", type: "Fruit", spacing: 36, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, rich compost", companionPlants: ["Corn", "Marigold", "Sunflower", "Nasturtium"], incompatiblePlants: ["Potato", "Cucumber"] },
  { name: "Strawberry", type: "Fruit", spacing: 12, sunlight: "Full Sun", water: "1-1.5 inches per week", fertilizer: "Balanced, slightly acidic", companionPlants: ["Lettuce", "Spinach", "Onion", "Bean", "Thyme", "Borage"], incompatiblePlants: ["Cabbage", "Broccoli", "Cauliflower"] },
  { name: "Blueberry", type: "Fruit", spacing: 48, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Acidic fertilizer", companionPlants: ["Strawberry", "Rhododendron", "Azalea", "Thyme"], incompatiblePlants: ["Walnut"] },
  { name: "Raspberry", type: "Fruit", spacing: 24, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, rich compost", companionPlants: ["Garlic", "Tansy", "Turnip", "Marigold"], incompatiblePlants: ["Potato", "Blackberry", "Tomato"] },
  { name: "Grape", type: "Fruit", spacing: 48, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, compost mulch", companionPlants: ["Hyssop", "Basil", "Clover", "Geranium"], incompatiblePlants: ["Cabbage", "Radish"] },
  { name: "Rosemary", type: "Herb", spacing: 24, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Light, low nitrogen", companionPlants: ["Carrot", "Bean", "Cabbage", "Sage", "Broccoli"], incompatiblePlants: ["Cucumber", "Mint"] },
  { name: "Thyme", type: "Herb", spacing: 12, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Light, balanced", companionPlants: ["Strawberry", "Cabbage", "Tomato", "Eggplant", "Rose"], incompatiblePlants: ["Basil", "Cilantro"] },
  { name: "Oregano", type: "Herb", spacing: 12, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Light, balanced", companionPlants: ["Basil", "Tomato", "Pepper", "Grape", "Bean"], incompatiblePlants: ["Mint"] },
  { name: "Cilantro", type: "Herb", spacing: 6, sunlight: "Partial Shade", water: "Keep soil moist", fertilizer: "Light, balanced", companionPlants: ["Tomato", "Spinach", "Lettuce", "Pea", "Anise"], incompatiblePlants: ["Fennel", "Dill"] },
  { name: "Dill", type: "Herb", spacing: 12, sunlight: "Full Sun", water: "Keep soil moist", fertilizer: "Light, balanced", companionPlants: ["Cabbage", "Onion", "Lettuce", "Cucumber", "Broccoli"], incompatiblePlants: ["Carrot", "Tomato", "Cilantro"] },
  { name: "Parsley", type: "Herb", spacing: 8, sunlight: "Full to Partial Sun", water: "Keep soil moist", fertilizer: "Balanced, rich compost", companionPlants: ["Tomato", "Asparagus", "Corn", "Rose", "Carrot"], incompatiblePlants: ["Lettuce", "Mint"] },
  { name: "Mint", type: "Herb", spacing: 18, sunlight: "Partial Shade", water: "Keep soil consistently moist", fertilizer: "Balanced, compost", companionPlants: ["Tomato", "Cabbage", "Pea", "Broccoli"], incompatiblePlants: ["Rosemary", "Oregano", "Parsley", "Lavender"] },
  { name: "Chives", type: "Herb", spacing: 6, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Light, balanced", companionPlants: ["Carrot", "Tomato", "Rose", "Lettuce", "Strawberry"], incompatiblePlants: ["Bean", "Pea"] },
  { name: "Sage", type: "Herb", spacing: 18, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Light, low nitrogen", companionPlants: ["Rosemary", "Cabbage", "Carrot", "Strawberry", "Tomato"], incompatiblePlants: ["Cucumber", "Basil", "Rue", "Onion"] },
  { name: "Lavender", type: "Herb", spacing: 18, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Very light, low nitrogen", companionPlants: ["Rose", "Thyme", "Sage", "Rosemary", "Oregano"], incompatiblePlants: ["Mint", "Basil"] },
  { name: "Lemongrass", type: "Herb", spacing: 24, sunlight: "Full Sun", water: "Keep soil moist", fertilizer: "High nitrogen", companionPlants: ["Tomato", "Pepper", "Marigold", "Citronella"], incompatiblePlants: [] },
  { name: "Tarragon", type: "Herb", spacing: 18, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Light, balanced", companionPlants: ["Eggplant", "Pepper", "Tomato"], incompatiblePlants: [] },
  { name: "Sunflower", type: "Flower", spacing: 24, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, moderate", companionPlants: ["Corn", "Cucumber", "Squash", "Lettuce", "Bean"], incompatiblePlants: ["Potato"] },
  { name: "Nasturtium", type: "Flower", spacing: 12, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Very light (poor soil is fine)", companionPlants: ["Tomato", "Cucumber", "Squash", "Radish", "Bean", "Cabbage"], incompatiblePlants: [] },
  { name: "Zinnia", type: "Flower", spacing: 6, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, light", companionPlants: ["Tomato", "Cucumber", "Squash", "Bean", "Pepper"], incompatiblePlants: [] },
  { name: "Petunia", type: "Flower", spacing: 12, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced liquid fertilizer", companionPlants: ["Tomato", "Squash", "Bean", "Pepper", "Asparagus"], incompatiblePlants: [] },
  { name: "Cosmos", type: "Flower", spacing: 12, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Very light (poor soil is fine)", companionPlants: ["Tomato", "Squash", "Bean", "Corn"], incompatiblePlants: [] },
  { name: "Borage", type: "Herb", spacing: 18, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Light, balanced", companionPlants: ["Tomato", "Strawberry", "Squash", "Cabbage", "Bean"], incompatiblePlants: [] },
  { name: "Chamomile", type: "Herb", spacing: 8, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Light, balanced", companionPlants: ["Cabbage", "Onion", "Cucumber", "Mint", "Basil"], incompatiblePlants: [] },
  { name: "Fennel", type: "Herb", spacing: 12, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Light, balanced", companionPlants: ["Dill"], incompatiblePlants: ["Tomato", "Pepper", "Bean", "Carrot", "Coriander", "Eggplant"] },
  { name: "Swiss Chard", type: "Vegetable", spacing: 6, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "High nitrogen", companionPlants: ["Bean", "Onion", "Cabbage", "Lettuce", "Radish"], incompatiblePlants: ["Corn", "Potato"] },
  { name: "Arugula", type: "Vegetable", spacing: 6, sunlight: "Partial Shade", water: "Keep soil moist", fertilizer: "Light, balanced", companionPlants: ["Carrot", "Onion", "Lettuce", "Spinach", "Bean"], incompatiblePlants: ["Strawberry"] },
  { name: "Brussels Sprout", type: "Vegetable", spacing: 24, sunlight: "Full Sun", water: "1-1.5 inches per week", fertilizer: "High nitrogen", companionPlants: ["Onion", "Garlic", "Beet", "Carrot", "Dill", "Sage"], incompatiblePlants: ["Tomato", "Strawberry", "Pole Bean"] },
  { name: "Leek", type: "Vegetable", spacing: 6, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "High nitrogen, compost", companionPlants: ["Carrot", "Celery", "Onion", "Strawberry"], incompatiblePlants: ["Bean", "Pea"] },
  { name: "Parsnip", type: "Vegetable", spacing: 4, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Low nitrogen", companionPlants: ["Pea", "Bean", "Garlic", "Radish", "Onion"], incompatiblePlants: ["Carrot", "Celery", "Dill"] },
  { name: "Kohlrabi", type: "Vegetable", spacing: 6, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, moderate", companionPlants: ["Beet", "Onion", "Cucumber", "Lettuce", "Thyme"], incompatiblePlants: ["Pepper", "Tomato", "Pole Bean", "Strawberry"] },
  { name: "Jalapeño", type: "Vegetable", spacing: 14, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, then high phosphorus", companionPlants: ["Basil", "Onion", "Carrot", "Tomato", "Marigold"], incompatiblePlants: ["Bean", "Fennel", "Kohlrabi"] },
  { name: "Habanero", type: "Vegetable", spacing: 18, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, high phosphorus", companionPlants: ["Basil", "Onion", "Carrot", "Tomato", "Marigold"], incompatiblePlants: ["Bean", "Fennel", "Kohlrabi"] },
  { name: "Cherry Tomato", type: "Vegetable", spacing: 24, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "High phosphorus/potassium", companionPlants: ["Basil", "Marigold", "Carrot", "Onion", "Parsley"], incompatiblePlants: ["Potato", "Cabbage", "Fennel"] },
  { name: "Roma Tomato", type: "Vegetable", spacing: 24, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "High phosphorus/potassium", companionPlants: ["Basil", "Marigold", "Carrot", "Onion", "Parsley"], incompatiblePlants: ["Potato", "Cabbage", "Fennel"] },
  { name: "Green Bean", type: "Vegetable", spacing: 6, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Low nitrogen (fixes own)", companionPlants: ["Corn", "Squash", "Cucumber", "Carrot", "Radish", "Strawberry"], incompatiblePlants: ["Onion", "Garlic", "Pepper", "Fennel"] },
  { name: "Snap Pea", type: "Vegetable", spacing: 4, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Low nitrogen (fixes own)", companionPlants: ["Carrot", "Corn", "Cucumber", "Radish", "Turnip"], incompatiblePlants: ["Onion", "Garlic", "Chives"] },
  { name: "Scallion", type: "Vegetable", spacing: 2, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, light", companionPlants: ["Carrot", "Lettuce", "Tomato", "Pepper", "Beet"], incompatiblePlants: ["Bean", "Pea"] },
  { name: "Shallot", type: "Vegetable", spacing: 6, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, moderate", companionPlants: ["Carrot", "Tomato", "Beet", "Lettuce", "Strawberry"], incompatiblePlants: ["Bean", "Pea", "Asparagus"] },
  { name: "Rhubarb", type: "Vegetable", spacing: 36, sunlight: "Full to Partial Sun", water: "1-2 inches per week", fertilizer: "Rich compost, balanced", companionPlants: ["Garlic", "Onion", "Strawberry", "Bean"], incompatiblePlants: ["Dock", "Melon"] },
  { name: "Artichoke", type: "Vegetable", spacing: 36, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Rich compost, high nitrogen", companionPlants: ["Sunflower", "Tarragon", "Pea"], incompatiblePlants: [] },
  { name: "Fig", type: "Fruit", spacing: 48, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, moderate", companionPlants: ["Rue", "Marigold", "Comfrey", "Nasturtium"], incompatiblePlants: [] },
  { name: "Blackberry", type: "Fruit", spacing: 36, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Balanced, rich compost", companionPlants: ["Tansy", "Hyssop", "Borage", "Bee Balm"], incompatiblePlants: ["Raspberry", "Potato", "Tomato"] },
  { name: "Lemon", type: "Fruit", spacing: 48, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Citrus-specific, high nitrogen", companionPlants: ["Basil", "Lavender", "Marigold", "Nasturtium"], incompatiblePlants: [] },
  { name: "Bee Balm", type: "Flower", spacing: 18, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Light, balanced", companionPlants: ["Tomato", "Pepper", "Squash", "Echinacea"], incompatiblePlants: [] },
  { name: "Echinacea", type: "Flower", spacing: 18, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Very light", companionPlants: ["Bee Balm", "Black-Eyed Susan", "Lavender"], incompatiblePlants: [] },
  { name: "Black-Eyed Susan", type: "Flower", spacing: 18, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Very light", companionPlants: ["Echinacea", "Lavender", "Daylily"], incompatiblePlants: [] },
  { name: "Dahlia", type: "Flower", spacing: 18, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "High potassium, low nitrogen", companionPlants: ["Marigold", "Sunflower", "Zinnia"], incompatiblePlants: [] },
  { name: "Rose", type: "Flower", spacing: 24, sunlight: "Full Sun", water: "1-2 inches per week", fertilizer: "Rose-specific, balanced", companionPlants: ["Garlic", "Chives", "Lavender", "Thyme", "Marigold", "Geranium"], incompatiblePlants: [] },
  { name: "Pansy", type: "Flower", spacing: 8, sunlight: "Partial Shade", water: "1 inch per week", fertilizer: "Balanced liquid fertilizer", companionPlants: ["Lettuce", "Spinach", "Carrot", "Viola"], incompatiblePlants: [] },
  { name: "Snapdragon", type: "Flower", spacing: 8, sunlight: "Full Sun", water: "1 inch per week", fertilizer: "Balanced, moderate", companionPlants: ["Tomato", "Bean", "Lettuce", "Marigold"], incompatiblePlants: [] },
  { name: "Sweet Pea", type: "Flower", spacing: 6, sunlight: "Full Sun", water: "Keep soil moist", fertilizer: "Low nitrogen (fixes own)", companionPlants: ["Bean", "Lettuce", "Spinach"], incompatiblePlants: ["Onion", "Garlic"] },
  { name: "Alyssum", type: "Flower", spacing: 6, sunlight: "Full Sun", water: "Allow soil to dry between watering", fertilizer: "Very light", companionPlants: ["Tomato", "Broccoli", "Potato", "Grape"], incompatiblePlants: [] },
  { name: "Calendula", type: "Flower", spacing: 12, sunlight: "Full to Partial Sun", water: "1 inch per week", fertilizer: "Light, balanced", companionPlants: ["Tomato", "Pepper", "Asparagus", "Pea", "Bean"], incompatiblePlants: [] },
];

export function searchPlantDatabase(query: string): PlantReference[] {
  if (!query || query.length < 2) return [];
  const lower = query.toLowerCase();
  return PLANT_DATABASE
    .filter(p => p.name.toLowerCase().includes(lower))
    .slice(0, 8);
}
